/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HoneyBee;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class HoneyBee extends javax.swing.JFrame {
    
    DefaultTableModel model;
    
    public HoneyBee() {
        initComponents();
        String [] judul ={"Nama pemesan","Nomor Meja","Nama Menu","Jumlah"};
        model =new DefaultTableModel(judul,0);
        tabelChart.setModel(model);
        tampilkan();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        desktopPane = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDonat = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPemesan = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        btnChart = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        donatPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        donatcokelat = new javax.swing.JLabel();
        donatPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        donatcokelat1 = new javax.swing.JLabel();
        donatPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        donatcokelat2 = new javax.swing.JLabel();
        donatPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        donatcokelat3 = new javax.swing.JLabel();
        pemesanPanel = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nomor_meja = new javax.swing.JTextField();
        nama_pemesan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        nama_menu = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelChart = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 153, 0));

        menuPanel.setBackground(new java.awt.Color(102, 51, 0));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Honey Bee");

        btnHome.setBackground(new java.awt.Color(255, 153, 51));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDonat.setBackground(new java.awt.Color(255, 153, 51));
        btnDonat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDonatMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText(" MENU");

        javax.swing.GroupLayout btnDonatLayout = new javax.swing.GroupLayout(btnDonat);
        btnDonat.setLayout(btnDonatLayout);
        btnDonatLayout.setHorizontalGroup(
            btnDonatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDonatLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnDonatLayout.setVerticalGroup(
            btnDonatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDonatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HoneyBee/logo-removebg-preview.png"))); // NOI18N

        btnPemesan.setBackground(new java.awt.Color(255, 153, 51));
        btnPemesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPemesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPemesanMousePressed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 51, 0));
        jLabel37.setText("PEMESAN");

        javax.swing.GroupLayout btnPemesanLayout = new javax.swing.GroupLayout(btnPemesan);
        btnPemesan.setLayout(btnPemesanLayout);
        btnPemesanLayout.setHorizontalGroup(
            btnPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPemesanLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(26, 26, 26))
        );
        btnPemesanLayout.setVerticalGroup(
            btnPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPemesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnChart.setBackground(new java.awt.Color(255, 153, 51));
        btnChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChartMousePressed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 51, 0));
        jLabel38.setText("CHART");

        javax.swing.GroupLayout btnChartLayout = new javax.swing.GroupLayout(btnChart);
        btnChart.setLayout(btnChartLayout);
        btnChartLayout.setHorizontalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChartLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel38)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        btnChartLayout.setVerticalGroup(
            btnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDonat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDonat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Selamat Datang ");

        jLabel9.setFont(new java.awt.Font("Colonna MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("di ");

        jLabel10.setFont(new java.awt.Font("BABELGAMEE", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Honey Bee Donat");

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("AYOO PESAN SEKARANG JUGA!!!");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homePanelLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1))
                        .addGroup(homePanelLayout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jLabel9))
                        .addComponent(jLabel10)))
                .addGap(388, 388, 388))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        donatPanel1.setBackground(new java.awt.Color(255, 255, 204));
        donatPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                donatPanel1MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 51, 0));
        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("HONEY DONAT");

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\Choco Paket.png")); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel7.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Donat Lembut dengan  ekstrak cokelat ");

        jLabel8.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("yang dipadukan dengan berbagai");

        jLabel13.setBackground(new java.awt.Color(102, 51, 0));
        jLabel13.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Macam Topping");

        jLabel15.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\arrow-right.png")); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        donatcokelat.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        donatcokelat.setForeground(new java.awt.Color(102, 51, 0));
        donatcokelat.setText("DONAT COKELAT");

        javax.swing.GroupLayout donatPanel1Layout = new javax.swing.GroupLayout(donatPanel1);
        donatPanel1.setLayout(donatPanel1Layout);
        donatPanel1Layout.setHorizontalGroup(
            donatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel1Layout.createSequentialGroup()
                .addGroup(donatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donatPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(donatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donatcokelat)
                            .addComponent(jLabel7)))
                    .addGroup(donatPanel1Layout.createSequentialGroup()
                        .addGap(703, 703, 703)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        donatPanel1Layout.setVerticalGroup(
            donatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(donatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donatPanel1Layout.createSequentialGroup()
                        .addComponent(donatcokelat)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(106, 106, 106))
        );

        mainPanel.add(donatPanel1, "card4");

        donatPanel2.setBackground(new java.awt.Color(255, 255, 204));
        donatPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                donatPanel2MousePressed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(102, 51, 0));
        jLabel23.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 51, 0));
        jLabel23.setText("HONEY DONAT");

        jLabel24.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\Strawberry.png")); // NOI18N
        jLabel24.setText("jLabel5");

        jLabel25.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 51, 0));
        jLabel25.setText("Donat Lembut dengan  ekstrak Strawberry");

        jLabel26.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 51, 0));
        jLabel26.setText("yang dipadukan dengan berbagai");

        jLabel27.setBackground(new java.awt.Color(102, 51, 0));
        jLabel27.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 51, 0));
        jLabel27.setText("Macam Topping");

        jLabel28.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\c9bde702-19dc-41bc-9e46-a1f35d262bf9.png")); // NOI18N
        jLabel28.setText("jLabel14");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\arrow-right.png")); // NOI18N
        jLabel29.setText("jLabel15");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });

        donatcokelat1.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        donatcokelat1.setForeground(new java.awt.Color(102, 51, 0));
        donatcokelat1.setText("DONAT STRAWBERRY");

        javax.swing.GroupLayout donatPanel2Layout = new javax.swing.GroupLayout(donatPanel2);
        donatPanel2.setLayout(donatPanel2Layout);
        donatPanel2Layout.setHorizontalGroup(
            donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donatPanel2Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(donatPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donatcokelat1))))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        donatPanel2Layout.setVerticalGroup(
            donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel2Layout.createSequentialGroup()
                .addGroup(donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(donatPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatcokelat1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(donatPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(donatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(106, 106, 106))
        );

        mainPanel.add(donatPanel2, "card4");

        donatPanel3.setBackground(new java.awt.Color(255, 255, 204));
        donatPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                donatPanel3MousePressed(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(102, 51, 0));
        jLabel30.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 51, 0));
        jLabel30.setText("HONEY DONAT");

        jLabel31.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\Blueberry.png")); // NOI18N
        jLabel31.setText("jLabel5");

        jLabel32.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 51, 0));
        jLabel32.setText("Donat Lembut dengan  ekstrak Blueberry");

        jLabel33.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 51, 0));
        jLabel33.setText("yang dipadukan dengan berbagai");

        jLabel34.setBackground(new java.awt.Color(102, 51, 0));
        jLabel34.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 51, 0));
        jLabel34.setText("Macam Topping");

        jLabel35.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\c9bde702-19dc-41bc-9e46-a1f35d262bf9.png")); // NOI18N
        jLabel35.setText("jLabel14");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel35MousePressed(evt);
            }
        });

        jLabel36.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\arrow-right.png")); // NOI18N
        jLabel36.setText("jLabel15");
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel36MousePressed(evt);
            }
        });

        donatcokelat2.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        donatcokelat2.setForeground(new java.awt.Color(102, 51, 0));
        donatcokelat2.setText("DONAT BLUEBERRY");

        javax.swing.GroupLayout donatPanel3Layout = new javax.swing.GroupLayout(donatPanel3);
        donatPanel3.setLayout(donatPanel3Layout);
        donatPanel3Layout.setHorizontalGroup(
            donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel3Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donatPanel3Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(donatPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donatcokelat2))))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        donatPanel3Layout.setVerticalGroup(
            donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(donatPanel3Layout.createSequentialGroup()
                        .addComponent(donatcokelat2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(donatPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(106, 106, 106))
        );

        mainPanel.add(donatPanel3, "card4");

        donatPanel4.setBackground(new java.awt.Color(255, 255, 204));
        donatPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                donatPanel4MousePressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(102, 51, 0));
        jLabel16.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 51, 0));
        jLabel16.setText("HONEY DONAT");

        jLabel17.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\Paket Eksklusif 1.png")); // NOI18N
        jLabel17.setText("jLabel5");

        jLabel18.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("Donat Lembut dibalut dengan Eksklusif ");

        jLabel19.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("yang dipadukan dengan berbagai");

        jLabel20.setBackground(new java.awt.Color(102, 51, 0));
        jLabel20.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 51, 0));
        jLabel20.setText("Macam Topping");

        jLabel21.setIcon(new javax.swing.ImageIcon("E:\\Kuliah IF UNJANI 2020\\Semester 3\\Pemrograman objek 1\\Tugas Besar\\AppMenu\\c9bde702-19dc-41bc-9e46-a1f35d262bf9.png")); // NOI18N
        jLabel21.setText("jLabel14");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });

        donatcokelat3.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        donatcokelat3.setForeground(new java.awt.Color(102, 51, 0));
        donatcokelat3.setText("PAKET DONAT EKSKLUSIF");

        javax.swing.GroupLayout donatPanel4Layout = new javax.swing.GroupLayout(donatPanel4);
        donatPanel4.setLayout(donatPanel4Layout);
        donatPanel4Layout.setHorizontalGroup(
            donatPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel4Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(donatPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(donatPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donatcokelat3))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        donatPanel4Layout.setVerticalGroup(
            donatPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(106, 106, 106))
            .addGroup(donatPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(donatcokelat3)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(donatPanel4, "card4");

        pemesanPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel41.setBackground(new java.awt.Color(102, 51, 0));
        jLabel41.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 51, 0));
        jLabel41.setText("PEMESAN");

        jLabel14.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("Nama Pemesan :");

        jLabel22.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 51, 0));
        jLabel22.setText("Nomor Meja      :");

        btnTambah.setBackground(new java.awt.Color(255, 153, 51));
        btnTambah.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(102, 51, 0));
        btnTambah.setText("Tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 51, 0));
        jLabel39.setText("Nama Menu      :");

        nama_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_menuActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("CentSchbkCyrill BT", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 51, 0));
        jLabel40.setText("Jumlah              :");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 153, 51));
        btnEdit.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 51, 0));
        btnEdit.setText("Edit Pesanan");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 153, 51));
        btnReset.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(102, 51, 0));
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pemesanPanelLayout = new javax.swing.GroupLayout(pemesanPanel);
        pemesanPanel.setLayout(pemesanPanelLayout);
        pemesanPanelLayout.setHorizontalGroup(
            pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesanPanelLayout.createSequentialGroup()
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pemesanPanelLayout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel41))
                    .addGroup(pemesanPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pemesanPanelLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pemesanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(nama_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pemesanPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(16, 16, 16)
                                    .addComponent(nama_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pemesanPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(18, 18, 18)
                                    .addComponent(nomor_meja, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pemesanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        pemesanPanelLayout.setVerticalGroup(
            pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesanPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel41)
                .addGap(70, 70, 70)
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(nama_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nomor_meja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(nama_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pemesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        mainPanel.add(pemesanPanel, "card2");

        chartPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel43.setBackground(new java.awt.Color(102, 51, 0));
        jLabel43.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 51, 0));
        jLabel43.setText("CHART");

        tabelChart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelChartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelChart);

        btnHapus.setBackground(new java.awt.Color(255, 153, 51));
        btnHapus.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(102, 51, 0));
        btnHapus.setText("Hapus Pesanan");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit3.setBackground(new java.awt.Color(255, 153, 51));
        btnEdit3.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 12)); // NOI18N
        btnEdit3.setForeground(new java.awt.Color(102, 51, 0));
        btnEdit3.setText("Edit Pesanan");
        btnEdit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartPanelLayout.createSequentialGroup()
                .addGroup(chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chartPanelLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel43))
                    .addGroup(chartPanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chartPanelLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel43)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        mainPanel.add(chartPanel, "card2");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1202, Short.MAX_VALUE))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jDesktopPane1.setLayer(desktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMousePressed

    private void donatPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_donatPanel1MousePressed

    private void btnDonatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonatMousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDonatMousePressed

    private void donatPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatPanel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_donatPanel4MousePressed

    private void donatPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_donatPanel2MousePressed

    private void donatPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatPanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_donatPanel3MousePressed

    private void btnPemesanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPemesanMousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(pemesanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPemesanMousePressed

    private void btnChartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChartMousePressed
         mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(chartPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnChartMousePressed

    private void jLabel36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MousePressed
      mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel4);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel36MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel2);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel3);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel29MousePressed

    private void jLabel35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel2);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel35MousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel3);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed
       mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(donatPanel1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel28MousePressed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(chartPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/honeybee", "root","");
            cn.createStatement().executeUpdate("insert into pemesanan values"+"('"+nama_pemesan.getText()+"', '"+nomor_meja.getText()+"', '"+nama_menu.getText()+"', '"+jumlah.getText()+"')");
            tampilkan();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Silakan dilengkapi!!");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void nama_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_menuActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(chartPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/honeybee", "root","");
            cn.createStatement().executeUpdate("update pemesanan set nomor_meja ='"+nomor_meja.getText()+"', nama_menu ='"+nama_menu.getText()+"', jumlah ='"+jumlah.getText()+"' where nama_pemesan ='"+nama_pemesan.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(HoneyBee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       try {
          Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/honeybee", "root","");
          cn.createStatement().executeUpdate("delete from pemesanan where nama_pemesan= '"+nama_pemesan.getText()+"'");
           tampilkan();
           reset();
       } catch (SQLException ex) {
           Logger.getLogger(HoneyBee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelChartMouseClicked
        int i = tabelChart.getSelectedRow();
        
        if (i>-1){
            nama_pemesan.setText(model.getValueAt(i, 0).toString());
            nomor_meja.setText(model.getValueAt(i, 1).toString());
            nama_menu.setText(model.getValueAt(i, 2).toString());
            jumlah.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tabelChartMouseClicked

    private void btnEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit3ActionPerformed
         mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(pemesanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnEdit3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed
private void reset(){
        nama_pemesan.setText("");
        nomor_meja.setText("");
        nama_menu.setText("");
        jumlah.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoneyBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoneyBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoneyBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoneyBee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoneyBee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnChart;
    private javax.swing.JPanel btnDonat;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit3;
    private javax.swing.JButton btnHapus;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnPemesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JPanel desktopPane;
    private javax.swing.JPanel donatPanel1;
    private javax.swing.JPanel donatPanel2;
    private javax.swing.JPanel donatPanel3;
    private javax.swing.JPanel donatPanel4;
    private javax.swing.JLabel donatcokelat;
    private javax.swing.JLabel donatcokelat1;
    private javax.swing.JLabel donatcokelat2;
    private javax.swing.JLabel donatcokelat3;
    private javax.swing.JPanel homePanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nama_menu;
    private javax.swing.JTextField nama_pemesan;
    private javax.swing.JTextField nomor_meja;
    private javax.swing.JPanel pemesanPanel;
    private javax.swing.JTable tabelChart;
    // End of variables declaration//GEN-END:variables

    private Object getDesktopPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void tampilkan() {
     
        int row = tabelChart.getRowCount();
        for(int a=0; a<row;a++){
            model.removeRow(0);
        }
        try {
          Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/honeybee", "root","");
          ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM pemesanan ");
          while(rs.next()){
              String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
              model.addRow(data);
          }
        } catch (SQLException ex) {
            Logger.getLogger(HoneyBee.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    
}
}
